name: news_checker
description: An HTTP API to check the type (such as fake, etc.) of news
author: Neel Kamath
homepage: https://github.com/neelkamath/news-checker

dependencies:
  postgres: ^1.0.0
  rpc: ^0.6.0
  string_processor: ^1.0.1

dev_dependencies:
  link_checker: ^2.0.1
  test: ^1.3.0

environment:
  sdk: '>=2.0.0 <3.0.0'